### ISSUE TITLE
Create Facebook Contact Provider

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Branch-iOS-Invite-SDK#15]
Ability to invite Facebook friends is one of the most desired features I believe. I have a local patch that attempts to accomplish the work, but have run into a wall in several areas.

* Actually getting contacts is not as simple as `/me/friends`, as the Graph API v2 only includes friends who've already installed the app, which doesn't seem to cover the base use case (inviting other users who aren't currently in the app to the app).  
** The `/me/invitable_frends` API would be perfect, but is only available to Facebook game apps with a canvas presence.  
** The `/me/taggable_friends` end point also returns useful information, but without the actual friend IDs (and I'm pretty sure this would be an abuse of their API).  
  
* There are a number of different dialogs available for sending various messages. I'm not sure which is the correct one, but I'm leaning towards 'AppRequests' dialog.

**Comment by hsavit1** [comment]
how is this coming along @shortstuffsushi ? Do you recommend the Facebook App Invites?

**Comment by shortstuffsushi** [comment]
Whoops, sorry @hsavit1 -- forgot to respond. At the moment, this is on hold for a couple reasons.

The primary one is still the above inability to make this work nicely for "all scenarios." However, there may be some things we can do with App Invites (as you mentioned) to make this work better. It isn't our top priority at the moment, though.

Feel free to contribute it back if you do attempt it, though :smile: Otherwise, it will likely be revisited within the next month or two.
