### ISSUE TITLE
Contacts should be filtered when Provider is changed

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Branch-iOS-Invite-SDK#20]
Currently, when a user switches contact providers (say, from Email to SMS), the filter text is not cleared, but the full contact list is shown.

When the contact provider is changed, the filter itself either needs to be cleared, or the contact list needs to be cleared. I'm of the opinion that as a user, I would prefer to keep my filter text and just see my contacts filtered accordingly.

**Comment by francisjervis** [comment]
This is my expected behavior.
