### ISSUE TITLE
Getting Error Loading Invite View

### ISSUE THREAD

**Issue by hsavit1** [BranchMetrics/Branch-iOS-Invite-SDK#25]
Hello,
I used the invite view the exact same way as the example project and Im getting this error

Any clues? thanks

 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </private/var/mobile/Containers/Bundle/Application/FAE52CEC-CBBE-4F92-A5D3-F8E68CA049AF/MyApp.app> (loaded)' with name 'BranchInviteViewController'Hello,

**Comment by shortstuffsushi** [comment]
Hi @hsavit1, sorry you're seeing issues. Can you tell me first how you're including the code? It appears that the bundle you have is missing the Invite Controller, though I'm not sure why that would be the case. I'll try to look into this shortly, but may not be able to get back to you with more info until tomorrow.

**Comment by hsavit1** [comment]
Thanks @shortstuffsushi for the quick reply. I've installed the BranchInvite through cocoapods, and most functions have been working smoothly thus far. I can see all of the files including the BranchInviteViewController Xib, however Xcode still gives me this NSInternalInconsistencyException at runtime.

**Comment by shortstuffsushi** [comment]
When you look at the Target Membership in Xcode, is that BranchInviteViewController.xib file ticked for the BranchInviteBundle?

**Comment by shortstuffsushi** [comment]
Like this

![screen shot 2015-06-21 at 6 07 22 pm](https://cloud.githubusercontent.com/assets/1016147/8273771/8addb994-1840-11e5-8fee-79dd5abe9974.png)

**Comment by hsavit1** [comment]
Yes, I think that was a very good question to ask, but unfortunately it looks exactly like that!  I will try a few more things and get back to you shortly

**Comment by hsavit1** [comment]
P.S. Im working with  an 8.0 deployment target xcode 6.3

**Comment by hsavit1** [comment]
interestingly, it gets through this method without crashing

+ (UINavigationController *)branchInviteViewControllerWithDelegate:(id <BranchInviteControllerDelegate>)delegate {
    NSBundle *branchInviteBundle = [BranchInviteBundleUtil branchInviteBundle];
    BranchInviteViewController *branchInviteController = [[BranchInviteViewController alloc] initWithNibName:@"BranchInviteViewController" bundle:branchInviteBundle];
    branchInviteController.delegate = delegate;

    return [[UINavigationController alloc] initWithRootViewController:branchInviteController];
}

**Comment by hsavit1** [comment]
Also ive tried most of the standard things like clean/build , deleting derived data, etc

**Comment by hsavit1** [comment]
so i did a little investigation, and the bundle does exist, although i had to do some hackery to actually get it

however, the class still cannot access the BranchInviteDefaultContactCell. When I check all the Nib contents in the bundle, I can't find any objects

+ (NSBundle *)branchInviteBundle {
    NSString *branchInviteBundlePath = [[NSBundle mainBundle] pathForResource:@"BranchInvite" ofType:@"bundle"];
    NSBundle *branchInviteBundle = [NSBundle bundleWithPath:branchInviteBundlePath];
    
    NSArray *allbundles = [NSBundle allBundles];
    NSBundle *bnd;
    for(NSBundle *bundle in allbundles){
        if ([bundle.resourcePath containsString:@"mobile/Containers"]) {
            bnd = bundle;
        }
    }
    
    return bnd;
}

+ (UINib *)nibNamed:(NSString *)nibName {
    NSBundle *branchInviteBundle = [BranchInviteBundleUtil branchInviteBundle];
    
    NSArray *n = [branchInviteBundle pathsForResourcesOfType:@"nib" inDirectory:branchInviteBundle.bundlePath];
    

    UINib *nib = [UINib nibWithNibName:nibName bundle:branchInviteBundle];
    
//    NSArray	*niby = [nib instantiateWithOwner:nil options:nil];
    
    return nib;
}

**Comment by shortstuffsushi** [comment]
@hsavit1 you can check the actual contents of a bundle on your file system -- a bundle is really just a directory. Could you locate it on your file system and see what's inside of it?

**Comment by hsavit1** [comment]
@shortstuffsushi  I decided it just wasn't worth it to continue going with this. I just installed the SDK manually and it works! Thanks for trying to help

**Comment by shortstuffsushi** [comment]
Oh, so you're only no longer using Cocoapods, and that resolved it for you? I'm curious - are you trying to develop an iPad app? I just ran across this, which may be of note. However, if you got it working, I may stop pursuing for now.

![screen shot 2015-06-21 at 11 13 10 pm](https://cloud.githubusercontent.com/assets/1016147/8275447/77b1c47a-186b-11e5-86a6-7000c8b526af.png)

**Comment by hsavit1** [comment]
Nope, iPhone. I decided to use the SDK instead. Still using cocoapods for other pods. Best of luck- I'm assuming this is Xcode not being nice but you never know. This is def a tough error to figure out, I'd suggest you move on to other things lol

**Comment by juanpdelat** [comment]
@shortstuffsushi I am having the same issue, I fixed it (hacked really) by adding manually the `resources` folder to my project, I am assuming there is an issue with that folder in the pod, although the `BranchWelcomeViewController` seems to be working correctly.

 I will try to dig a little further tomorrow.

**Comment by shortstuffsushi** [comment]
Hi @juanpdelat. Thanks for digging. I'm actually not working with Branch anymore, or maintaining this project, if you need help from our end, try @aaustin or @danwalkowski

**Comment by danwalkowski** [comment]
These issues are due to a build configuration problem that I haven't sorted out yet.  The example app runs  fine in the simulator, but -only- on iPhones, which I believe is just a lucky coincidence.  It crashes immediately  if you try to run it on an iPad, because it can't load the invite  xibs.

**Comment by fogunkoya** [comment]
@aaustin Hi there Auston was this issue ever sorted out?

**Comment by aaustin** [comment]
Yes - this should be resolved now due to the commits in Feb! I'm closing the ticket out.

**Comment by rankinit** [comment]
Getting this issue on the latest branchio  using CocoaPods.  *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/5300DA99-B369-446D-8F5E-A04D66D988AB/MyApp.app> (loaded)' with name 'BranchInviteViewController''

**Comment by xeo-it** [comment]
same here

**Comment by papanton** [comment]
same issue here for latest version using swift

**Comment by francisjervis** [comment]
See #40
