### ISSUE TITLE
Getting build error when added through pods in Swift

### ISSUE THREAD

**Issue by rishabhtayal** [BranchMetrics/Branch-iOS-Invite-SDK#29]
Here is my ```podfile```. Gives error on ```#import "HMSegmentControl.h"``` statement in ```BranchInviteControllerDelegate.h``` file.

```
source 'https://github.com/CocoaPods/Specs.git'

platform:ios, '7.0'

inhibit_all_warnings!
use_frameworks!

pod 'Branch'
pod 'BranchInvite'
```

**Comment by shortstuffsushi** [comment]
Hey @rishabhtayal, sorry about that. I'm assuming you're running into the issue that is fixed in #27, but could be more sure if you provided me with the error you're seeing.

**Comment by rishabhtayal** [comment]
@shortstuffsushi I don't have much information. It just says HMSegmentControl.h not found.

**Comment by shortstuffsushi** [comment]
Oh, my mistake. I thought you were saying that you were seeing an error while executing `pod install`. 

I'm unsure why you wouldn't see that file come through, but I'm thinking the easiest thing to do would be just to clean your project in Xcode (try cmd+option+shift+k). If that doesn't do it, try removing the `Podfile.lock` and `Pods` directory again, and then rerun `pod install`.

Perhaps there is an error being emitted by Cocoapods while it tries to pull HMSegmentedControl that is causing those files to never make it to Xcode. Sorry I can't give much more info, but I think you're seeing an issue with Cocoapods, and not the Invite SDK itself. Let me know if those steps give you any more insight.

**Comment by francisjervis** [comment]
Hi Rishabh, I’ve had some experience implementing Branch invite in Swift. This may be a header file issue - can you post the relevant lines from your bridging.h (or whatever) file?

The installation is a little non-standard in that it seems to want each of the headers to be imported separately, like so:

#import <Branch/Branch.h>
#import <BranchInvite/BranchInvite.h>
#import <BranchInvite/BranchInviteViewController.h>
#import <BranchInvite/BranchInviteTextContactProvider.h>
#import <BranchInvite/BranchInviteEmailContactProvider.h>
#import <BranchInvite/BranchWelcomeView.h>
#import <BranchInvite/BranchWelcomeViewController.h>
#import <BranchInvite/BranchWelcomeControllerDelegate.h>
#import <BranchInvite/BranchWelcomeDefaultView.h>

My *guess* is that you didn’t import InviteViewController correctly, and that is causing the dependency not to be found. Just a guess tho!
Good luck
Francis

**Comment by rishabhtayal** [comment]
@shortstuffsushi Please the attached gif. I have created a swift project from scratch. Let me know if you need more detail. The project builds fine when only ```Branch``` module is imported but gives an error when ```BranchInvite``` module is imported.

![untitled](https://cloud.githubusercontent.com/assets/2100166/9209539/abf9d512-403c-11e5-931d-ebe1ea480f47.gif)

**Comment by rishabhtayal** [comment]
@francisjervis There is no bridging header file since I am using ```use_frameworks!``` in my ```Podfile```.

**Comment by francisjervis** [comment]
That may be the problem, in fact. Have you tried to replicate this *not* using frameworks?

**Comment by rishabhtayal** [comment]
@francisjervis I am sure it will work fine when not using frameworks option. But that is the issue here. The library gives error when used as a framework in swift.

**Comment by shortstuffsushi** [comment]
Unfortunately, I'm not very familiar with the `use_frameworks` options, or what the implications of that are with this SDK. Is there something that we would need to do differently to support it?

**Comment by rishabhtayal** [comment]
@shortstuffsushi I might be able to help you fix this issue.

**Comment by francisjervis** [comment]
Yes but I don’t know what ;) It’s also highly possible this is an issue with HMSegmentedControl. 

I haven’t found use_frameworks has enough advantages to justify dealing with issues like this, so I don’t use it. I think I did in a side-project that *only* used Swift-based libraries, and that worked OK. But IIRC setting that flag in your podfile breaks FBSDK and/or Google Analytics too, so this is not a rare issue with ObjC based SDKs.

**Comment by rishabhtayal** [comment]
@francisjervis it's happening when you use ```use_frameworks``` but the underlying error is not something related to swift or frameworks. I think it's the way file is imported. Eventually most of the people are using frameworks in cocoapods.

**Comment by francisjervis** [comment]
There is an ongoing issue with frameworks, see for example https://github.com/CocoaPods/CocoaPods/issues/3194 <https://github.com/CocoaPods/CocoaPods/issues/3194>

Seems like a CocoaPods issue, but this thread is somewhat beyond my comfort zone…I just went with the use_libraries workaround.

**Comment by rishabhtayal** [comment]
Just FYI, this merge will fix this issue. https://github.com/BranchMetrics/Branch-iOS-Invite-SDK/pull/30
