### ISSUE TITLE
'Could not build Obj-C module 'BranchInvite'

### ISSUE THREAD

**Issue by samyoungnyc** [BranchMetrics/Branch-iOS-Invite-SDK#32]
I've been following the instructions for implementing this SDK... below is what I have in my Podfile: 

platform :ios, '8.0'

use_frameworks!

target 'My-App' do

pod 'BranchInvite'

end

And here is the error I'm getting... I've done a lot of troubleshooting to try and figure out the problem, looked at past issues of this sort, and for some reason I cannot get "BranchWelcomeViewController" (nor BranchInvite) to be recognized/imported. Any idea what I'm doing wrong here? Do I need to populate my bridging-header? 

PS: I'm using Xcode 7, Swift 2, OS X 10.10.5, and the latest version of Cocoapods. 

Thanks

![screen shot 2015-10-18 at 7 49 16 pm](https://cloud.githubusercontent.com/assets/4691011/10567781/251cabda-75db-11e5-887c-dbb5ae5618b2.png)

**Comment by derrickstaten** [comment]
Please try adding to the bridging header, yes. Please let us know if you continue to experience these issues after that

**Comment by derrickstaten** [comment]
We'll try to recreate when we can. Are you using Cocoapods for any other SDKs / have you had problems using them in your Swift project?

**Comment by samyoungnyc** [comment]
This is the first time I've used Cocoapods for a project. I avoid Cocoapods generally but in this case wanted to try it out. I may try integrating the project the old-fashioned way, if this proves to be to troublesome a problem.

**Comment by francisjervis** [comment]
NB the correct bridging header imports for Branch Invite are not entirely standard - the following works for me (just importing BranchInvite.h did not):


#import <Branch/Branch.h>
#import <BranchInvite/BranchInvite.h>
#import <BranchInvite/BranchInviteViewController.h>
#import <BranchInvite/BranchInviteTextContactProvider.h>
#import <BranchInvite/BranchInviteEmailContactProvider.h>
#import <BranchInvite/BranchWelcomeView.h>
#import <BranchInvite/BranchWelcomeViewController.h>
#import <BranchInvite/BranchWelcomeControllerDelegate.h>
#import <BranchInvite/BranchWelcomeDefaultView.h>

**Comment by samyoungnyc** [comment]
Hi @francisjervis - when I do this, I get 55-60 errors mostly one of the following: 

Duplicate interface definition of 'BranchXFile' is ignored
                                  OR
Property has a previous declaration

**Comment by francisjervis** [comment]
That’s odd. Though I am not using frameworks, so it may be something to do with that. Can you try un-installing (comment out all the [pod ‘podname’] lines and run pod update) then re-install without using frameworks? If  what you posted is your complete pod file (i.e. you are only using Branch not a whole bunch of other frameworks) this might be an easy workaround.

**Comment by samyoungnyc** [comment]
Tried your instructions... No dice. Very frustrating - thanks though.

**Comment by francisjervis** [comment]
Try taking the imports for Branch and BranchInvite out of your AppDelegate. I get a spurious “module not found” error (this, again, w/o frameworks) if I include them - without the import line

class AppDelegate: UIResponder, UIApplicationDelegate, BranchWelcomeControllerDelegate {
}

works for me.

**Comment by danwalkowski** [comment]
This should be working fine as of my last commit.
