### ISSUE TITLE
Crash after app went in brackground

### ISSUE THREAD

**Issue by eikebartels** [BranchMetrics/Branch-iOS-Invite-SDK#42]
Hey, I noticed a crash. It looks like it comes from the close request. It happens after the app went in background 

![screen shot 2016-03-03 at 11 44 37](https://cloud.githubusercontent.com/assets/767979/13491922/751aab44-e135-11e5-9cde-8dd7b49a2397.png)
![screen shot 2016-03-03 at 11 44 49](https://cloud.githubusercontent.com/assets/767979/13491924/77201f46-e135-11e5-9521-ce56d95eb59e.png)

**Comment by aaustin** [comment]
@eikebartels Not sure if you ever resolved this but I can't seem to reproduce. Do you have some more context that you could share? Maybe a crashlytics link?
