### ISSUE TITLE
BranchInviteControllerDelegate Swift

### ISSUE THREAD

**Issue by rankinit** [BranchMetrics/Branch-iOS-Invite-SDK#43]
Error Message: ViewController.swift:  Type 'ViewController' does not conform to protocol 'BranchInviteControllerDelegate'

However I implemented both required methods like so:
class ViewController : UITableViewController, UITextFieldDelegate, BranchInviteControllerDelegate {
 func inviteControllerDidFinish() {
    print("inviteControllerDidFinish")
  }
  
   func inviteControllerDidCancel() {
    print("inviteControllerDidCancel")
  }
}
Still getting this compiler error. I closed and reopen Xcode to no avail.

Branch (0.12.2)
Xcode 7.3

**Comment by rankinit** [comment]
There was a third method that needed to be implemented. invitingUserFullname()  but it was not easy to see in a sea of optional methods.

**Comment by henryhardy** [comment]
If you create a working swift project can you share it somewhere?
