### ISSUE TITLE
Update to support 0.12.4

### ISSUE THREAD

**Issue by francisjervis** [BranchMetrics/Branch-iOS-Invite-SDK#45]
Need to replace getReferralUrlWithParams with updated methods.

**Comment by aaustin** [comment]
Ah! I'm on it.

**Comment by francisjervis** [comment]
Me too! Getting a “no visible @interface” error when I try to change to

getShortURLWithParams:invitingUserParams andChannel:channel andFeature:"invitation" andCallback:^(NSString *url, NSError *error)

though.

Francis Jervis

Sent from
https://polymail.io/

On Fri, Jul 15, 2016 at 7:34 PM Alex Austin

<
mailto:Alex Austin <notifications@github.com>
> wrote:

Ah! I'm on it.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/BranchMetrics/Branch-iOS-Invite-SDK/issues/45#issuecomment-233103821
, or

**Comment by aaustin** [comment]
Hmm ... that's definitely in the header:
```- (void)getShortURLWithParams:(NSDictionary *)params andChannel:(NSString *)channel andFeature:(NSString *)feature andCallback:(callbackWithUrl)callback;```

**Comment by francisjervis** [comment]
![screen shot 2016-07-15 at 7 40 23 pm](https://cloud.githubusercontent.com/assets/10519862/16892332/098ec7fe-4ac4-11e6-8524-8b5e04accbd9.png)

**Comment by aaustin** [comment]
ah! terminate your starting bracket
