### ISSUE TITLE
Pod Integration, no visible interface

### ISSUE THREAD

**Issue by papanton** [BranchMetrics/Branch-iOS-Invite-SDK#48]
Hello, I am trying to integrate BranchInvite along with Branch in my swift project. I am using cocoapods -v 1.0.1, Branch 0.12.4 and BranchInvite 0.3.8. The error I am getting is on a function in BranchInviteViewController in the screenshot bellow.  I have cleaned, deleted derived data, reintegrated and integrated pods to no avail. Have you guys seen this before ?

![screen shot 2016-07-20 at 6 39 58 pm](https://cloud.githubusercontent.com/assets/3289183/17008867/2a32357e-4eaa-11e6-9a67-3107bdf04c0f.png)

**Comment by francisjervis** [comment]
This is fixed, actually - just waiting for the pod to be updated!

@aaustin ready to release w #46 & #47?

**Comment by papanton** [comment]
cool, ill keep an eye out

**Comment by aaustin** [comment]
I actually did up the pod I thought. Let me check..

**Comment by aaustin** [comment]
Ack - had an error that I misread. It's been published. Sorry guys.
