### ISSUE TITLE
Black welcome screen when use_frameworks! set in Podfile

### ISSUE THREAD

**Issue by francisjervis** [BranchMetrics/Branch-iOS-Invite-SDK#49]
Edit: this appears to be a resource bundle issue:
https://guides.cocoapods.org/syntax/podspec.html#resource_bundles

(based on this https://github.com/CocoaPods/CocoaPods/issues/2408 )

**Comment by mwawrusch** [comment]
Any ETA on this? It's blocking us pushing out the new version.

**Comment by francisjervis** [comment]
@aaustin just to confirm this is not fixed in 0.3.10

**Comment by aaustin** [comment]
Hey guys - I'll look at this on Sunday. Sorry for the delay.

**Comment by aaustin** [comment]
It's this issue: https://github.com/CocoaPods/CocoaPods/issues/3226 😦

**Comment by aaustin** [comment]
working on a fix

**Comment by aaustin** [comment]
Deployed in 0.3.11. Please let me know if it resolves it for you both.

**Comment by mwawrusch** [comment]
Works now, thank you so much.

**Comment by aaustin** [comment]
Nice 👍
