### ISSUE TITLE
BranchInviteDefaultContactCell make Xcodebuild error

### ISSUE THREAD

**Issue by a455455b** [BranchMetrics/Branch-iOS-Invite-SDK#53]
when I use --xcodebuild build a ipa, sometimes this command error at BranchInviteDefaultContactCell.xib 
Environmental:Xcode 9.1

**Comment by E-B-Smith** [comment]
Thanks for the heads up!  Let me look into it.

**Comment by E-B-Smith** [comment]
I've updated the project for Xcode 9, including the xibs. I think this will fix your problem.

The new version is 0.3.11.

**Comment by a455455b** [comment]
thanks a lot !
